### PR TITLE
Sign up routing

### PR DESCRIPTION
**Pull request by joesakkab**
This will rout ethe user from the sign-up page to the search page is the sign-up is successful.

### CODE REVIEW

**Comment by joesakkab** [comment]
Hello everyone, please approve the search page pull request, then approve this one, as most of the merge conflicts are resolved in the other pull request,

**Review by twarep — COMMENTED** [review]
Looks good overall.

One problem is that when signing up as a service provider, while this does take you to the search page, it does not load the new listing under the search page. You need to refresh the page in order for the new provider to show in the list.

**Comment by joesakkab** [comment]
Hey peter, I would assume that signing up as a service provider wouldn't take you to the search page, but would take you to the inbox page. I don't think we have a ticket or user story that specifies a contractor being able to view other contractors. For now, i can change it to take you to the inbox page.

**Comment by twarep** [comment]
Closed as these changes are already covered.

**Pull request closed without merging**
